# Copyright (c) 2016 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Mainflux
site_description: Mainflux IoT System
site_author: Drasko DRASKOVIC
site_url: http://mainflux.io

# Repository
repo_name: GitHub
repo_url: https://github.com/mainflux/mainflux

# Copyright
copyright: Copyright (c) 2016 Mainflux

# Documentation and theme
theme: 'readthedocs'

# Options
extra:
  logo: images/logo.png
  palette:
    primary: 'cyan'
    accent: 'teal'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  github:
    download_release: false
  author:
    github: mainflux/mainflux
    twitter: mainflux

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

pages:
- Home: index.md
- Getting Started: getting-started.md
- Security: security.md
- CLI: cli.md
- API Reference: api.md
- DevOps: devops.md
- Community: community.md
- FAQ: faq.md
- License: license.md
