graph LR
    A["NGINX"] --- B["HTTP-Core"];
    B --- F["MongoDB"]

    A --- C["MQTT - WS"];
    A --- K["CoAP"];
	A --- D["Auth"];

	B --- E["NATS"]
	C --- E
	D --- E
	D --- R["Redis"]
	K --- E

	E --- T["Telegraf"]
	T --- L["InfluxDB"]
	L --- N["Kapacitor"]

    I["Mainflux UI"] --- A
    J["Mainflux CLI"] --- A
    G["Device"] --- A
    H["App"] --- A
