graph LR
    A["NGINX"] --- B["HTTP-Core"];
    B --- F["MongoDB"]

    A --- C["MQTT - WS"];
	A --- D["Auth"];
	D --- R["Redis"]

	B --- E["NATS"]
	C --- E
	D --- E

    I["Mainflux UI"] --- A
    J["Mainflux CLI"] --- A
    G["Device"] --- A
    H["App"] --- A
